export const getAllProblems= async (req, res, next)=>{
    try{

    }
    catch(error){
        next(error);
    }
}

export const getProblemDetails= async (req, res, next)=>{
    try{

    }
    catch(error){
        next(error);
    }
}

export const createProblem= async (req, res, next)=>{
    try{

    }
    catch(error){
        next(error);
    }
}

